<?php

namespace AppBundle\Repository;

/**
 * GrocerylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrocerylistRepository extends \Doctrine\ORM\EntityRepository
{
}
