<?php

namespace AppBundle\Repository;

/**
 * GrocerylistItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrocerylistItemRepository extends \Doctrine\ORM\EntityRepository
{
}
