<?php

namespace AppBundle\Repository;

/**
 * RecipeItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeItemRepository extends \Doctrine\ORM\EntityRepository
{
}
