<?php

namespace App\Repository;

/**
 * GrocerylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrocerylistRepository extends \Doctrine\ORM\EntityRepository
{
    public function showListsOfCurrentUser($userId) 
    {
        $qb = $this->createQueryBuilder('g')
            ->where('g.userId = :value')->setParameter('value', $userId)
            ->orderBy('g.name', 'ASC');
        return $qb;
    }
}
