<?php

namespace App\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function showListsOfCurrentUser($userId) 
    {
        $qb = $this->createQueryBuilder('t')
            ->where('t.user = :value')->setParameter('value', $userId)
            ->orderBy('t.name', 'ASC');
        return $qb;
    }

    public function findAllTagsOfCurrentUser($userId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT tag
                FROM App:Tag tag
                WHERE tag.user = :value'
            )->setParameter('value', $userId)
            ->getResult();
    }

    public function findAllTagsOfUser($userId) 
    {
        $qb = $this->createQueryBuilder('t')
            ->where('t.user = :value')->setParameter('value', $userId)
            ->orderBy('t.name', 'ASC');
        return $qb;
    }
}
