<?php

namespace App\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function showListsOfCurrentUser($userId) 
    {
        $qb = $this->createQueryBuilder('t')
            ->where('t.userId = :value')->setParameter('value', $userId)
            ->orderBy('t.name', 'ASC');
        return $qb;
    }
}
